=== joseluis-martin/solnotsimpl_js/xml/facturacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.registradores.org/schema/externos/xmldsig-core-schema.xsd"/>
  <xs:element name="corpme-floti-facturacion">
    <xs:annotation>
      <xs:documentation>Elemento raíz</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:sequence>
          <xs:element name="facturacion">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="factura" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="id" type="xs:ID" use="required"/>
              <xs:attribute name="importe-base" type="dinero" use="required"/>
              <xs:attribute name="importe-impuesto" type="dinero" use="required"/>
              <xs:attribute name="periodo-inicio" type="xs:date" use="required"/>
              <xs:attribute name="periodo-fin" type="xs:date" use="required"/>
            </xs:complexType>
          </xs:element>
          <xs:element ref="ds:Signature"/>
        </xs:sequence>
        <xs:element name="error">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="codigo" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="ok">
          <xs:complexType/>
        </xs:element>
      </xs:choice>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="emisor" type="actor"/>
        <xs:element name="destinatario" type="actor"/>
        <xs:element name="importe">
          <xs:complexType>
            <xs:attribute name="base" type="dinero" use="required"/>
            <xs:attribute name="impuesto" type="dinero" use="required"/>
            <xs:attribute name="irpf" type="dinero" use="required"/>
            <xs:attribute name="total" type="dinero" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element ref="peticion" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="serie" type="xs:string" use="required"/>
      <xs:attribute name="numero" type="xs:integer" use="required"/>
      <xs:attribute name="ejercicio" type="xs:int" use="required"/>
      <xs:attribute name="fecha" type="xs:date" use="required"/>
      <xs:attribute name="regimen-caja" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Indica si la factura se ha generado acogiéndose al régimen especial de caja. Si no está presente, se asume que es false.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="actor">
    <xs:attribute name="nombre" type="xs:string" use="required"/>
    <xs:attribute name="nif" type="xs:string" use="required"/>
    <xs:attribute name="domicilio" type="xs:string" use="required"/>
    <xs:attribute name="municipio" type="xs:string" use="required"/>
    <xs:attribute name="provincia" type="xs:string" use="required"/>
    <xs:attribute name="cp" type="xs:int" use="required"/>
  </xs:complexType>
  <xs:simpleType name="dinero">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="peticion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="arancel" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="importe" type="dinero" use="required"/>
                <xs:attribute name="veces-aplicado" type="xs:int"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="grupo" type="xs:string" use="required"/>
      <xs:attribute name="usuario" type="xs:string" use="required"/>
      <xs:attribute name="fecha" type="xs:dateTime" use="required"/>
      <xs:attribute name="fecha-respuesta" type="xs:dateTime" use="required"/>
      <xs:attribute name="tipo" type="xs:int" use="required"/>
      <xs:attribute name="importe-base" type="dinero" use="required"/>
      <xs:attribute name="porcentaje-impuesto" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="destino" type="xs:string" use="required"/>
      <xs:attribute name="referencia" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== joseluis-martin/solnotsimpl_js/xml_facturas_recibidas/2024_11_21_Facturacion.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<corpme-floti-facturacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="F11767" xsi:noNamespaceSchemaLocation="http://www.registradores.org/schema/floti/facturacion.xsd">
  <facturacion id="GTREGAPP" importe-base="144.32" importe-impuesto="27.47" periodo-fin="2024-10-31" periodo-inicio="2024-10-01">
    <factura ejercicio="2024" fecha="2024-10-31" numero="313" regimen-caja="false" serie="Z2">
      <emisor cp="6900" domicilio="C/ Francisco de Peñaranda, nº 3" municipio="LLERENA" nif="76654376T" nombre="JULIO SOTO ANTUNEZ" provincia="BADAJOZ"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="lourdesdiaz@grupotasvalor.es" fecha="2024-10-31T11:18:00Z" fecha-respuesta="2024-10-31T11:28:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PN29H4" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_33_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="523" regimen-caja="false" serie="Z5">
      <emisor cp="8760" domicilio="Ausias March, esq. Verge del Tiscar, s/n " municipio="MARTORELL" nif="52605703B" nombre="ESTHER RADA PELEGRI" provincia="BARCELONA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-31T10:47:00Z" fecha-respuesta="2024-10-31T11:41:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PN16H7" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_32_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="367" regimen-caja="false" serie="Z4">
      <emisor cp="11630" domicilio="Pedro Almodovar 4-6" municipio="ARCOS DE LA FRONTERA" nif="31649244W" nombre="MARIA JESUS VOZMEDIANO TORRES" provincia="CADIZ"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="18.04" impuesto="3.79" irpf="2.71" total="19.12"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-30T09:30:00Z" fecha-respuesta="2024-10-31T08:25:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PF37C4" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_29_1" tipo="0" usuario="GTREGAPP"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-30T09:30:00Z" fecha-respuesta="2024-10-31T08:26:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PF37H6" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_30_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="532" regimen-caja="false" serie="Z5">
      <emisor cp="11204" domicilio="Calle Salvador Cabrera s/n. Edificio Registro" municipio="ALGECIRAS" nif="1494355E" nombre="EDUARDO-JOSE MARTINEZ GARCIA" provincia="CADIZ"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-30T09:20:00Z" fecha-respuesta="2024-10-31T08:26:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PF31N2" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_28_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="245" regimen-caja="false" serie="Z1">
      <emisor cp="15810" domicilio="Lugo 2 , 1º Izquierda" municipio="ARZUA" nif="48152969P" nombre="BEATRIZ MARIA BELMAR MADRID" provincia="A CORUÑA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-23T08:33:00Z" fecha-respuesta="2024-10-23T11:20:00Z" grupo="GRUPO TASVALOR, S.A." id="F48MT37Q8" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_21_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="494" regimen-caja="true" serie="Z6">
      <emisor cp="15300" domicilio="Doctor Jose Fariña, 3 - bajo" municipio="BETANZOS" nif="33255159B" nombre="JESUS FERNANDEZ BREA" provincia="A CORUÑA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="27.06" impuesto="5.68" irpf="4.06" total="28.68"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-24T10:01:00Z" fecha-respuesta="2024-10-25T05:33:00Z" grupo="GRUPO TASVALOR, S.A." id="F48NC69T9" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_23_1" tipo="0" usuario="GTREGAPP"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-24T10:40:00Z" fecha-respuesta="2024-10-25T05:59:00Z" grupo="GRUPO TASVALOR, S.A." id="F48NC90N3" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_24_1" tipo="0" usuario="GTREGAPP"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-24T10:40:00Z" fecha-respuesta="2024-10-25T06:10:00Z" grupo="GRUPO TASVALOR, S.A." id="F48NC90N4" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_25_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="349" regimen-caja="false" serie="Z9">
      <emisor cp="15100" domicilio="Luis Calvo Sanz, 32 Bajo." municipio="CARBALLO" nif="32833615B" nombre="PATRICIA OLIVEROS VILLAR" provincia="A CORUÑA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-22T12:34:00Z" fecha-respuesta="2024-10-23T06:28:00Z" grupo="GRUPO TASVALOR, S.A." id="F48MP89F0" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_20_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="544" regimen-caja="false" serie="Z5">
      <emisor cp="15006" domicilio="Novoa Santos 5 y 7" municipio="CORUÑA (A)" nif="19887420X" nombre="ENRIQUE RODRIGUEZ LLORENS" provincia="A CORUÑA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-23T14:35:00Z" fecha-respuesta="2024-10-24T09:33:00Z" grupo="GRUPO TASVALOR, S.A." id="F48MZ01U2" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_22_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="497" regimen-caja="false" serie="Z6">
      <emisor cp="20018" domicilio="Plaza Julio Caro Baroja, 1 - 1º" municipio="SAN SEBASTIAN" nif="34102911Y" nombre="MARIA MICAELA CURTO ERASO" provincia="GUIPUZCOA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="lourdesdiaz@grupotasvalor.es" fecha="2024-10-31T11:18:00Z" fecha-respuesta="2024-10-31T12:38:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PN29H6" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_34_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="803" regimen-caja="false" serie="Z6">
      <emisor cp="25006" domicilio="Paseo de Ronda, 87-89, altillo (Pasaje Brasilia)" municipio="LLEIDA" nif="07500018V" nombre="JESUS SANZ FERNANDEZ" provincia="LLEIDA"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="1.89" irpf="1.35" total="9.56"/>
      <peticion destino="grupotasvalor@grupotasvalor.es" fecha="2024-10-18T08:32:00Z" fecha-respuesta="2024-10-21T06:38:00Z" grupo="GRUPO TASVALOR, S.A." id="F48HU41M7" importe-base="9.02" porcentaje-impuesto="21" referencia="RF_18_3" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="305" regimen-caja="false" serie="Z1">
      <emisor cp="35007" domicilio="Emilio Castelar, 4-6, 3ª planta - Edif. Internacional" municipio="PALMAS DE GRAN CANARIA (LAS)" nif="51517967Z" nombre="BEATRIZ ZAMORA RODRIGUEZ" provincia="LAS PALMAS"/>
      <destinatario cp="28034" domicilio="Calle Manuel Tovar, 16 - Planta Segunda" municipio="MADRID" nif="A80639990" nombre="GRUPO TASVALOR SA" provincia="MADRID"/>
      <importe base="9.02" impuesto="0.63" irpf="1.35" total="8.30"/>
      <peticion destino="jptrujillo@grupotasvalor.es" fecha="2024-10-30T08:49:00Z" fecha-respuesta="2024-10-30T09:28:00Z" grupo="GRUPO TASVALOR, S.A." id="F48PF17C6" importe-base="9.02" porcentaje-impuesto="7" referencia="RF_27_1" tipo="0" usuario="GTREGAPP"/>
    </factura>
    <factura ejercicio="2024" fecha="2024-10-31" numero="681" regimen-caja="false" serie="Z8">
      <emisor cp="43004" domicilio="Pons Icart, 2" municipio="TARRAGONA" nif="16533946M" nombre="JOAQUIN MARIA LARRONDO LIZARRAGA" provincia="TARRAGONA"/>
